// <auto-generated />
using System;
using InvoiceApiProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceApiProject.Migrations
{
    [DbContext(typeof(InvoiceApiProjectContext))]
    [Migration("20230924113457_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceApiProject.Models.Artikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Cena")
                        .HasColumnType("real")
                        .HasColumnName("cena");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ime");

                    b.HasKey("Id");

                    b.ToTable("artikli_table");
                });

            modelBuilder.Entity("InvoiceApiProject.Models.Organizacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ime");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("opis");

                    b.HasKey("Id");

                    b.ToTable("organisation_table");
                });

            modelBuilder.Entity("InvoiceApiProject.Models.Racun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_creation");

                    b.Property<int>("OrgId")
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    b.Property<int>("StrankaId")
                        .HasColumnType("int")
                        .HasColumnName("stranka_id");

                    b.Property<float>("Znesek")
                        .HasColumnType("real")
                        .HasColumnName("znesek");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("StrankaId");

                    b.ToTable("racuni_table");
                });

            modelBuilder.Entity("RacunVrstica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int")
                        .HasColumnName("article_id");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("RacunId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("RacunId");

                    b.ToTable("line_items");
                });

            modelBuilder.Entity("Stranka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ime");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("naslov");

                    b.HasKey("Id");

                    b.ToTable("stranka_table");
                });

            modelBuilder.Entity("InvoiceApiProject.Models.Racun", b =>
                {
                    b.HasOne("InvoiceApiProject.Models.Organizacija", "Organizacija")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stranka", "Stranka")
                        .WithMany()
                        .HasForeignKey("StrankaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacija");

                    b.Navigation("Stranka");
                });

            modelBuilder.Entity("RacunVrstica", b =>
                {
                    b.HasOne("InvoiceApiProject.Models.Artikel", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceApiProject.Models.Racun", "Racun")
                        .WithMany("LineItems")
                        .HasForeignKey("RacunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Racun");
                });

            modelBuilder.Entity("InvoiceApiProject.Models.Racun", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
